version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: test
          command: yarn test
